# .ruff.toml — конфиг для Ruff

# Основные настройки
line-length = 120  # Максимальная длина строки для кода
indent-width = 4   # Ширина отступа

# Настройки линтера
[lint]
select = ["ALL"]  # Проверять все правила

ignore = [
    "RUF001", # Игнорирование похожих символов с разными ASCII (Unicode confusables)
    "RUF002", # Игнорирование похожих символов с разными ASCII (Unicode confusables)
    "RUF003", # Игнорирование похожих символов с разными ASCII (Unicode confusables)
    "INP001", # Игнорирование ошибок namespace-пакета (требует __init__.py)
    "D203",   # Лишняя пустая строка перед определением класса
    "D213",   # Неправильная вторая строка многострочного docstring
    "S101",   # Использование обычного assert
    "S105",   # Жёстко зашитый пароль
    "N812",   # Импорт в верхнем регистре вместо lowercase (например, EC)
    "D100",   # Отсутствует docstring в модуле
    "D102",   # Отсутствует docstring в публичном методе
     "PGH003", # Игнорирование требования указывать конкретный код при `# type: ignore`
]